### ISSUE TITLE
When adding a user in different group, move it instead of adding him/her to the second group

### ISSUE THREAD

**Issue by durf1** [afklm/atlasman#31]
When adding people to a group, check if he/she is not belonging to another group of the same project.
If so, prompt the user if he/she wants to move him/her from the previous group to this one.

**Comment by Nehon** [comment]
IMO that's a bad idea, for the following reasons:
- People may be members of different groups, for example admin and developers. I know that in afklm an admin is also a dev, but that may not be the case in other companies.
- It's not that easy to implement, because we have to notify the user that it's been done else it will be very counter intuitive for him.

It would be a lot easier, and more flexible to keep it the simple way.

**Comment by mvdkleijn** [comment]
As per decision: will not do this.
